# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.trigger_verification_email200_response import TriggerVerificationEmail200Response

class TestTriggerVerificationEmail200Response(unittest.TestCase):
    """TriggerVerificationEmail200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerVerificationEmail200Response:
        """Test TriggerVerificationEmail200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerVerificationEmail200Response`
        """
        model = TriggerVerificationEmail200Response()
        if include_optional:
            return TriggerVerificationEmail200Response(
                message = 'verification email sent successfully'
            )
        else:
            return TriggerVerificationEmail200Response(
                message = 'verification email sent successfully',
        )
        """

    def testTriggerVerificationEmail200Response(self):
        """Test TriggerVerificationEmail200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
