# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.create_prompt_payload201_response import CreatePromptPayload201Response

class TestCreatePromptPayload201Response(unittest.TestCase):
    """CreatePromptPayload201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePromptPayload201Response:
        """Test CreatePromptPayload201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePromptPayload201Response`
        """
        model = CreatePromptPayload201Response()
        if include_optional:
            return CreatePromptPayload201Response(
                payload = px0.models.prompt_payload.PromptPayload(
                    id = '', 
                    prompt_id = '', 
                    name = '', 
                    variables = {user=Arpit, role=Admin}, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return CreatePromptPayload201Response(
                payload = px0.models.prompt_payload.PromptPayload(
                    id = '', 
                    prompt_id = '', 
                    name = '', 
                    variables = {user=Arpit, role=Admin}, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testCreatePromptPayload201Response(self):
        """Test CreatePromptPayload201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
