# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.create_org_request import CreateOrgRequest

class TestCreateOrgRequest(unittest.TestCase):
    """CreateOrgRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrgRequest:
        """Test CreateOrgRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrgRequest`
        """
        model = CreateOrgRequest()
        if include_optional:
            return CreateOrgRequest(
                name = 'Acme Corp'
            )
        else:
            return CreateOrgRequest(
                name = 'Acme Corp',
        )
        """

    def testCreateOrgRequest(self):
        """Test CreateOrgRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
