# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.create_prompt_request import CreatePromptRequest

class TestCreatePromptRequest(unittest.TestCase):
    """CreatePromptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePromptRequest:
        """Test CreatePromptRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePromptRequest`
        """
        model = CreatePromptRequest()
        if include_optional:
            return CreatePromptRequest(
                name = 'My Prompt',
                description = 'Useful prompt',
                slug = 'my_prompt'
            )
        else:
            return CreatePromptRequest(
                name = 'My Prompt',
        )
        """

    def testCreatePromptRequest(self):
        """Test CreatePromptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
