# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.get_admin_inbox200_response import GetAdminInbox200Response

class TestGetAdminInbox200Response(unittest.TestCase):
    """GetAdminInbox200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAdminInbox200Response:
        """Test GetAdminInbox200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAdminInbox200Response`
        """
        model = GetAdminInbox200Response()
        if include_optional:
            return GetAdminInbox200Response(
                inbox = [
                    px0.models.inbox_item.InboxItem(
                        id = '', 
                        team_id = '', 
                        team_name = '', 
                        user_id = '', 
                        user_email = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetAdminInbox200Response(
        )
        """

    def testGetAdminInbox200Response(self):
        """Test GetAdminInbox200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
