# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.register_request import RegisterRequest

class TestRegisterRequest(unittest.TestCase):
    """RegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterRequest:
        """Test RegisterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterRequest`
        """
        model = RegisterRequest()
        if include_optional:
            return RegisterRequest(
                email = 'user@example.com',
                password = 'secretpassword123',
                team_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
            )
        else:
            return RegisterRequest(
                email = 'user@example.com',
                password = 'secretpassword123',
        )
        """

    def testRegisterRequest(self):
        """Test RegisterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
