# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.list_org_people200_response import ListOrgPeople200Response

class TestListOrgPeople200Response(unittest.TestCase):
    """ListOrgPeople200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOrgPeople200Response:
        """Test ListOrgPeople200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOrgPeople200Response`
        """
        model = ListOrgPeople200Response()
        if include_optional:
            return ListOrgPeople200Response(
                people = [
                    px0.models.user.User(
                        id = '', 
                        email = '', 
                        is_verified = True, 
                        is_admin = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page = 56,
                limit = 56,
                total = 56
            )
        else:
            return ListOrgPeople200Response(
                people = [
                    px0.models.user.User(
                        id = '', 
                        email = '', 
                        is_verified = True, 
                        is_admin = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page = 56,
                limit = 56,
                total = 56,
        )
        """

    def testListOrgPeople200Response(self):
        """Test ListOrgPeople200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
