# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.trigger_password_reset200_response import TriggerPasswordReset200Response

class TestTriggerPasswordReset200Response(unittest.TestCase):
    """TriggerPasswordReset200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerPasswordReset200Response:
        """Test TriggerPasswordReset200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerPasswordReset200Response`
        """
        model = TriggerPasswordReset200Response()
        if include_optional:
            return TriggerPasswordReset200Response(
                message = 'password reset email sent successfully'
            )
        else:
            return TriggerPasswordReset200Response(
                message = 'password reset email sent successfully',
        )
        """

    def testTriggerPasswordReset200Response(self):
        """Test TriggerPasswordReset200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
