# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.list_api_keys200_response import ListAPIKeys200Response

class TestListAPIKeys200Response(unittest.TestCase):
    """ListAPIKeys200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAPIKeys200Response:
        """Test ListAPIKeys200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAPIKeys200Response`
        """
        model = ListAPIKeys200Response()
        if include_optional:
            return ListAPIKeys200Response(
                api_keys = [
                    px0.models.api_key.APIKey(
                        id = '', 
                        name = '', 
                        org_id = '', 
                        team_id = '', 
                        key_prefix = 'ak_1a2b3c4d', 
                        operation = 'read_render', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListAPIKeys200Response(
                api_keys = [
                    px0.models.api_key.APIKey(
                        id = '', 
                        name = '', 
                        org_id = '', 
                        team_id = '', 
                        key_prefix = 'ak_1a2b3c4d', 
                        operation = 'read_render', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListAPIKeys200Response(self):
        """Test ListAPIKeys200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
