# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from px0.models.diff_versions200_response import DiffVersions200Response

class TestDiffVersions200Response(unittest.TestCase):
    """DiffVersions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiffVersions200Response:
        """Test DiffVersions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiffVersions200Response`
        """
        model = DiffVersions200Response()
        if include_optional:
            return DiffVersions200Response(
                from_version = 1,
                to_version = 2,
                from_template = 'Hello {{ .name }}',
                to_template = 'Hello {{ .name }}!
Welcome to px0.',
                diff = '--- v1
+++ v2
@@ -1 +1,2 @@
-Hello {{ .name }}
+Hello {{ .name }}!
+Welcome to px0.
'
            )
        else:
            return DiffVersions200Response(
                from_version = 1,
                to_version = 2,
                from_template = 'Hello {{ .name }}',
                to_template = 'Hello {{ .name }}!
Welcome to px0.',
                diff = '--- v1
+++ v2
@@ -1 +1,2 @@
-Hello {{ .name }}
+Hello {{ .name }}!
+Welcome to px0.
',
        )
        """

    def testDiffVersions200Response(self):
        """Test DiffVersions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
