# coding: utf-8

"""
    px0 API

    Core API for px0, a modern prompt management, versioning, and execution service.  This specification serves as the source of truth for downstream code generation, including Documentation, SDKs, CLIs, and Model Context Protocol (MCP) servers. All endpoints are rigorously validated against this specification at test time to ensure absolute zero-drift between implementation and documentation. 

    The version of the OpenAPI document: 1.0.0
    Contact: arpit@arpitbhayani.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class APIKey(BaseModel):
    """
    APIKey
    """ # noqa: E501
    id: StrictStr = Field(description="Unique API Key identifier.")
    name: StrictStr = Field(description="Human-readable name given to the API key.")
    org_id: StrictStr = Field(description="UUID of the organization.")
    team_id: Optional[StrictStr] = Field(default=None, description="Optional UUID of the team.")
    key_prefix: StrictStr = Field(description="First characters of the API Key used for visual identification.")
    operation: StrictStr = Field(description="The scope of operations.")
    created_at: datetime = Field(description="Timestamp when the API Key was created.")
    last_used_at: Optional[datetime] = Field(default=None, description="Timestamp when the API Key was last used. Null if never used.")
    __properties: ClassVar[List[str]] = ["id", "name", "org_id", "team_id", "key_prefix", "operation", "created_at", "last_used_at"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['read_render', 'all', 'admin']):
            raise ValueError("must be one of enum values ('read_render', 'all', 'admin')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "team_id": obj.get("team_id"),
            "key_prefix": obj.get("key_prefix"),
            "operation": obj.get("operation"),
            "created_at": obj.get("created_at"),
            "last_used_at": obj.get("last_used_at")
        })
        return _obj


